#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CardFlight.Sample.Resource", IsApplication=true)]

namespace CardFlight.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int textSize = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int DKGRAY = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int blue = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int half_transparent = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int primary = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int primary_disabled = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int primary_off = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int primary_pressed = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int stubhub_blue = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int text_disabled = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int text_pressed = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int text_primary = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int translucent_black = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int transparent = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int warning = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060007
			public const int big_text_size = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int checkout_input_field_text_size = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int content_padding = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int field_height = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int field_holder_margin = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int large_text_size = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int reg_text_size = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int regular_text_size = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int small_text_size = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int standard_padding = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int text_field_height = 2131099651;
			
			// aapt resource value: 0x7f06000e
			public const int text_size = 2131099662;
			
			// aapt resource value: 0x7f060005
			public const int zip_code_width = 2131099653;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_selector_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_selector_text = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_top_border = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cardflight_logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int checkmark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int checkout_accepted_cards = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int checkout_card_amex = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int checkout_card_cvc = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int checkout_card_discover = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int checkout_card_master = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int checkout_card_paypal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int checkout_card_visa = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int checkout_default_card = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int checkout_header_gradient = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int checkout_next_btn_bg = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int checkout_payment_icons = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int drawer_selector_background = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int drawer_selector_text = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int edit_text = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int edit_text_holo_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_action_search = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_drawer = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_launcher = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int reader_top_finger = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int reader_top_off = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int reader_top_on = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int text_field_bg = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int textfield_activated_holo_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int textfield_activated_holo_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int textfield_bg_activated_holo_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int textfield_bg_default_holo_dark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int textfield_bg_disabled_focused_holo_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int textfield_bg_disabled_holo_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int textfield_bg_focused_holo_dark = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int textfield_default = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int textfield_default_holo_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int textfield_default_holo_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int textfield_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int textfield_disabled_focused_holo_dark = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int textfield_disabled_focused_holo_light = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int textfield_disabled_holo_dark = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int textfield_disabled_holo_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int textfield_disabled_selected = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int textfield_focused_holo_dark = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int textfield_focused_holo_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int textfield_longpress_holo = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int textfield_multiline_activated_holo_dark = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int textfield_multiline_activated_holo_light = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int textfield_multiline_default_holo_dark = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int textfield_multiline_default_holo_light = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int textfield_multiline_disabled_focused_holo_dark = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int textfield_multiline_disabled_focused_holo_light = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int textfield_multiline_disabled_holo_dark = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int textfield_multiline_disabled_holo_light = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int textfield_multiline_focused_holo_dark = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int textfield_multiline_focused_holo_light = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int textfield_pressed = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int textfield_pressed_holo = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int textfield_search_default = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int textfield_search_default_holo_dark = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int textfield_search_default_holo_light = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int textfield_search_empty_default = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int textfield_search_empty_pressed = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int textfield_search_empty_selected = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int textfield_search_pressed = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int textfield_search_selected = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int textfield_selected = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int toast_background = 2130837572;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09002f
			public const int android_version_text = 2131296303;
			
			// aapt resource value: 0x7f09002a
			public const int authorizeCard = 2131296298;
			
			// aapt resource value: 0x7f09001d
			public const int autoConfigButton = 2131296285;
			
			// aapt resource value: 0x7f090000
			public const int bluetoothOptions = 2131296256;
			
			// aapt resource value: 0x7f09000e
			public const int bluetooth_pair_list = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int bt_reader_holder_off = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int bt_reader_holder_on = 2131296268;
			
			// aapt resource value: 0x7f090005
			public const int cardEditText = 2131296261;
			
			// aapt resource value: 0x7f090018
			public const int card_icon = 2131296280;
			
			// aapt resource value: 0x7f090023
			public const int card_last_four = 2131296291;
			
			// aapt resource value: 0x7f090017
			public const int card_num_holder = 2131296279;
			
			// aapt resource value: 0x7f090022
			public const int card_number = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int card_type = 2131296289;
			
			// aapt resource value: 0x7f090026
			public const int charge_amount = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int charge_captured = 2131296295;
			
			// aapt resource value: 0x7f090029
			public const int charge_refund = 2131296297;
			
			// aapt resource value: 0x7f090025
			public const int charge_token = 2131296293;
			
			// aapt resource value: 0x7f090028
			public const int charge_voided = 2131296296;
			
			// aapt resource value: 0x7f090001
			public const int connectToReader = 2131296257;
			
			// aapt resource value: 0x7f09000a
			public const int connecting_progress_bar = 2131296266;
			
			// aapt resource value: 0x7f090014
			public const int content_frame = 2131296276;
			
			// aapt resource value: 0x7f090010
			public const int credit_card_no = 2131296272;
			
			// aapt resource value: 0x7f090013
			public const int drawer_layout = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int drawer_list_text = 2131296274;
			
			// aapt resource value: 0x7f09001a
			public const int expiration = 2131296282;
			
			// aapt resource value: 0x7f090019
			public const int extra_fields = 2131296281;
			
			// aapt resource value: 0x7f090020
			public const int fetchZipCodeButton = 2131296288;
			
			// aapt resource value: 0x7f090011
			public const int last_four_digits = 2131296273;
			
			// aapt resource value: 0x7f090015
			public const int left_drawer = 2131296277;
			
			// aapt resource value: 0x7f09000f
			public const int paired_prompt = 2131296271;
			
			// aapt resource value: 0x7f090016
			public const int price_field = 2131296278;
			
			// aapt resource value: 0x7f09002b
			public const int processCapture = 2131296299;
			
			// aapt resource value: 0x7f090008
			public const int processPaymentButton = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int readerAddress = 2131296258;
			
			// aapt resource value: 0x7f090004
			public const int reader_status = 2131296260;
			
			// aapt resource value: 0x7f09002d
			public const int refundCard = 2131296301;
			
			// aapt resource value: 0x7f090006
			public const int resetFieldsButton = 2131296262;
			
			// aapt resource value: 0x7f09002e
			public const int sdk_version_text = 2131296302;
			
			// aapt resource value: 0x7f09001b
			public const int security_code = 2131296283;
			
			// aapt resource value: 0x7f090003
			public const int serialNumber = 2131296259;
			
			// aapt resource value: 0x7f09001e
			public const int swipeCardButton = 2131296286;
			
			// aapt resource value: 0x7f090007
			public const int tokenizeCard = 2131296263;
			
			// aapt resource value: 0x7f09002c
			public const int voidCard = 2131296300;
			
			// aapt resource value: 0x7f09000b
			public const int wizard_helper = 2131296267;
			
			// aapt resource value: 0x7f090009
			public const int wizard_status = 2131296265;
			
			// aapt resource value: 0x7f09001c
			public const int zip_code = 2131296284;
			
			// aapt resource value: 0x7f090024
			public const int zip_code_field = 2131296292;
			
			// aapt resource value: 0x7f09001f
			public const int zip_code_switch = 2131296287;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int bluetooth_fragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int bt_prompt_connect = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int bt_prompt_pair = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int bt_prompt_turn_on = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int card_holder = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int drawer_list_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int main_activity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int payment_dialog = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int payment_view = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int shuttle_fragment = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int splash_fragmant = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int idt_unimagcfg_default = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int idt_unimagcfg_default_old = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070012
			public const int _cvv_ = 2131165202;
			
			// aapt resource value: 0x7f07001f
			public const int app_name = 2131165215;
			
			// aapt resource value: 0x7f070016
			public const int attempt_auto_connect = 2131165206;
			
			// aapt resource value: 0x7f070039
			public const int auth_card = 2131165241;
			
			// aapt resource value: 0x7f070018
			public const int bluetooth_help_one = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int bluetooth_help_two = 2131165209;
			
			// aapt resource value: 0x7f07001d
			public const int bluetooth_pair_instructions_one = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int bluetooth_pair_instructions_two = 2131165212;
			
			// aapt resource value: 0x7f070017
			public const int bluetooth_problems_prompt = 2131165207;
			
			// aapt resource value: 0x7f070035
			public const int bluetooth_reader = 2131165237;
			
			// aapt resource value: 0x7f07001a
			public const int bluetooth_wizard_welcome = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int bluetooth_wizzard_get_started = 2131165211;
			
			// aapt resource value: 0x7f070015
			public const int bt_mag_reader_paired = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int bt_pair_instructions = 2131165204;
			
			// aapt resource value: 0x7f070010
			public const int card_mock = 2131165200;
			
			// aapt resource value: 0x7f070028
			public const int card_number = 2131165224;
			
			// aapt resource value: 0x7f070000
			public const int cardio_app_name = 2131165184;
			
			// aapt resource value: 0x7f07000a
			public const int cardio_cancel = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int cardio_cvv = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int cardio_cvv_hint = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int cardio_done = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int cardio_expires = 2131165192;
			
			// aapt resource value: 0x7f070005
			public const int cardio_expires_hint = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int cardio_name = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardio_name_hint = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int cardio_number = 2131165190;
			
			// aapt resource value: 0x7f070003
			public const int cardio_number_hint = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int cardio_reset = 2131165195;
			
			// aapt resource value: 0x7f070030
			public const int carflight_sdk_sandbox = 2131165232;
			
			// aapt resource value: 0x7f070027
			public const int credit_card_hint = 2131165223;
			
			// aapt resource value: 0x7f070011
			public const int credit_card_number_field_description = 2131165201;
			
			// aapt resource value: 0x7f07002b
			public const int currency = 2131165227;
			
			// aapt resource value: 0x7f070029
			public const int cvv_hint = 2131165225;
			
			// aapt resource value: 0x7f07002c
			public const int description = 2131165228;
			
			// aapt resource value: 0x7f07002e
			public const int drawer_close = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int drawer_open = 2131165229;
			
			// aapt resource value: 0x7f07001e
			public const int emptyList = 2131165214;
			
			// aapt resource value: 0x7f07000d
			public const int error_invalid_card_no = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int expiration_field_desc = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int expiration_field_hint = 2131165199;
			
			// aapt resource value: 0x7f07002a
			public const int expire_date_hint = 2131165226;
			
			// aapt resource value: 0x7f07003d
			public const int fetch_zip_code = 2131165245;
			
			// aapt resource value: 0x7f070022
			public const int manual_entry = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int person_name = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int person_name_hint = 2131165222;
			
			// aapt resource value: 0x7f070020
			public const int price = 2131165216;
			
			// aapt resource value: 0x7f070034
			public const int quantity = 2131165236;
			
			// aapt resource value: 0x7f070037
			public const int reader_address = 2131165239;
			
			// aapt resource value: 0x7f07003c
			public const int refund_charge = 2131165244;
			
			// aapt resource value: 0x7f070036
			public const int reset_fields = 2131165238;
			
			// aapt resource value: 0x7f07003a
			public const int run_auto_config = 2131165242;
			
			// aapt resource value: 0x7f070023
			public const int send_swipe_data = 2131165219;
			
			// aapt resource value: 0x7f070033
			public const int serial_number = 2131165235;
			
			// aapt resource value: 0x7f070031
			public const int shuttle_reader_demo = 2131165233;
			
			// aapt resource value: 0x7f07002f
			public const int splash_intro_text = 2131165231;
			
			// aapt resource value: 0x7f070021
			public const int swipe_card = 2131165217;
			
			// aapt resource value: 0x7f070038
			public const int test_capture = 2131165240;
			
			// aapt resource value: 0x7f070024
			public const int test_charge = 2131165220;
			
			// aapt resource value: 0x7f070032
			public const int test_tokenize = 2131165234;
			
			// aapt resource value: 0x7f07000c
			public const int title_activity_manual_entry = 2131165196;
			
			// aapt resource value: 0x7f07003b
			public const int void_charge = 2131165243;
			
			// aapt resource value: 0x7f070013
			public const int zip_code = 2131165203;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080005
			public const int ActionBarStyle = 2131230725;
			
			// aapt resource value: 0x7f080000
			public const int AppBaseTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int AppTheme = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int Button = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int CheckoutAddCardField = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int CheckoutZipField = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int Theme_NoBackground = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int TitleTextStyle = 2131230726;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PaymentView = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public const int PaymentView_textSize = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
